resolver: nightly-2022-06-06
packages:
- kvstore-effectful
- kvstore-effectful-spec
- kvstore-effectful-statemap
- kvstore-effectful-cache

extra-deps:
- git: https://github.com/haskell-effectful/effectful
  commit: f95b08cd3f33695c0ddef2db61f009a0c6a8e7aa
  subdirs:
  - effectful-core
  - effectful-th
  - effectful

- git: https://github.com/haskell-effectful/cache-effectful
  commit: e9d2427bfbfa0ebc7a7b960b103354981d246379
  # nix-sha256: 0gqvd3fmswraqi1gs8nrq7g68lsd69387japn3565mc09nr1qlfq
